gantt
  title Roadmap
  dateFormat  YYYY-MM-DD
  section Intake
  Access & Validation     :a1, 2025-08-09, 1d
  section Analysis
  Parse & Summarize       :a2, 1d
  Visuals & Presentation  :a3, 1d
  Review & Publish        :a4, 1d
