name: Automated Code Quality Review and Copilot Guidance

on:
  push:
    branches:
      - '**'

jobs:
  quality-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'

      - name: Install dependencies
        run: npm ci

      - name: Run TypeScript type check
        id: tsc
        run: npx tsc --noEmit

      - name: Run ESLint
        id: eslint
        run: npx eslint . --ext .js,.ts

      - name: Run Prettier check
        id: prettier
        run: npx prettier --check .

      - name: Run ShellCheck on shell scripts
        id: shellcheck
        run: |
          find . -type f -name "*.sh" -exec shellcheck {} +

      - name: Detect errors and prepare report
        id: detect_error
        run: |
          ERR=0
          if [ "${{ steps.tsc.outcome }}" = "failure" ]; then ERR=1; fi
          if [ "${{ steps.eslint.outcome }}" = "failure" ]; then ERR=1; fi
          if [ "${{ steps.prettier.outcome }}" = "failure" ]; then ERR=1; fi
          if [ "${{ steps.shellcheck.outcome }}" = "failure" ]; then ERR=1; fi
          if [ "$ERR" -eq 1 ]; then
            echo "There were code errors or quality issues. This will auto-create an issue and a PR for Copilot to review." > error_report.txt
            echo "::set-output name=error::true"
          else
            echo "::set-output name=error::false"
          fi

      - name: Create issue for code quality errors
        if: steps.detect_error.outputs.error == 'true'
        uses: peter-evans/create-issue-from-file@v5
        with:
          title: "Code Quality Review Needed (Automated)"
          content-filepath: error_report.txt
          assignees: dzp5103
          labels: review, copilot

      - name: Create Pull Request for automated fixes
        if: steps.detect_error.outputs.error == 'true'
        uses: peter-evans/create-pull-request@v7
        with:
          title: "Automated Code Quality Fixes (Copilot Review)"
          body: |
            This PR addresses code quality issues detected by the automated workflow.
            Copilot will be assigned for AI-powered review and fix suggestions.
          assignees: dzp5103
          labels: auto-fix, copilot-review
