name: Copilot Auto-Fix

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  copilot-fix:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Copilot Auto Review
        uses: github/copilot-actions/review@latest
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
      # Add steps here to apply Copilot's suggestions automatically if/when supported
